[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = '0.8.28'
src = 'src'
test = 'test'
out = 'out'
via_ir = true
verbosity = 3
libs = [
    # ./lib are refered in toolbox-foundry/lib
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]
auto_detect_remappings = false


remappings = [
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@openzeppelin/contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/heroglyph-library/lib/openzeppelin-contracts/contracts/',
    'ds-test/=node_modules/ds-test/src',
    'erc4626-tests/=node_modules/@layerzerolabs/toolbox-foundry/lib/heroglyph-library/lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/src',
    'heroglyph-library/=node_modules/@layerzerolabs/toolbox-foundry/lib/heroglyph-library/src',
    'openzeppelin-contracts/=node_modules/@layerzerolabs/toolbox-foundry/lib/heroglyph-library/lib/openzeppelin-contracts/',
    'solady/=node_modules/@layerzerolabs/toolbox-foundry/lib/solady/src',
    'solidity-bytes-utils/=node_modules/solidity-bytes-utils/',
]

[profile.e2e]
match_path = "test/e2e/*"

[profile.unit]
block_number = 17373196
block_timestamp = 1685467379
no_match_path = "test/e2e/*"

[fuzz]
runs = 1024
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
ethereum = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
arbitrum = "${RPC_ARBITRUM}"


[etherscan]
ethereum = { key = "${ETHERSCAN_KEY}", chain = 1, url = "https://api.etherscan.io/api/"}
sepolia = { key = "${ETHERSCAN_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api/"}
arbitrum = { key = "${ARBISCAN_KEY}", chain = 42161, url = "https://api.arbiscan.io/api/"}



[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config